"""Type stub for mechcalc.core.units

此文件为 Pylance / VS Code 提供类型提示，
units.py 中的 __getattr__ 动态生成这些函数。
"""

from typing import Any, Dict, List, Optional, Union
from pint import UnitRegistry

# 全局对象
ureg: UnitRegistry
Q_: Any

# 分类单位字典
NESTED_UNITS: Dict[str, Dict[str, str]]
FLAT_UNITS: Dict[str, str]

# 基础单位快捷函数
def kg(value: Any) -> Any: ...
def g(value: Any) -> Any: ...
def mg(value: Any) -> Any: ...
def t(value: Any) -> Any: ...

def mm(value: Any) -> Any: ...
def cm(value: Any) -> Any: ...
def dm(value: Any) -> Any: ...
def m(value: Any) -> Any: ...
def km(value: Any) -> Any: ...
def um(value: Any) -> Any: ...
def nm(value: Any) -> Any: ...

def N(value: Any) -> Any: ...
def kN(value: Any) -> Any: ...
def kgf(value: Any) -> Any: ...

def Pa(value: Any) -> Any: ...
def kPa(value: Any) -> Any: ...
def MPa(value: Any) -> Any: ...
def bar(value: Any) -> Any: ...
def psi(value: Any) -> Any: ...

def J(value: Any) -> Any: ...
def kJ(value: Any) -> Any: ...
def MJ(value: Any) -> Any: ...

def W(value: Any) -> Any: ...
def kW(value: Any) -> Any: ...
def MW(value: Any) -> Any: ...

def Nm(value: Any) -> Any: ...
def Nmm(value: Any) -> Any: ...
def kgfm(value: Any) -> Any: ...

def rpm(value: Any) -> Any: ...
def Hz(value: Any) -> Any: ...

def s(value: Any) -> Any: ...
def ms(value: Any) -> Any: ...
def min(value: Any) -> Any: ...
def h(value: Any) -> Any: ...

def deg(value: Any) -> Any: ...
def rad(value: Any) -> Any: ...

def L(value: Any) -> Any: ...
def mL(value: Any) -> Any: ...

# 组合单位
def kg_m2(value: Any) -> Any: ...
def kg_m3(value: Any) -> Any: ...
def m_min(value: Any) -> Any: ...
def m_s(value: Any) -> Any: ...
def m_s2(value: Any) -> Any: ...
def mm_s(value: Any) -> Any: ...
def g_cm3(value: Any) -> Any: ...
def Pa_s(value: Any) -> Any: ...
def cP(value: Any) -> Any: ...

# 工具函数
def to_mag(qty: Any, unit: Optional[str] = None) -> float: ...
def to_unit(qty: Any, unit: Optional[str] = None, compact: bool = True) -> str: ...
def ensure_quantity(value: Any, unit: Optional[str] = None) -> Any: ...
def ensure_float(value: Any, unit: Optional[str] = None) -> float: ...
def as_quantity(value: Any, unit: str) -> Any: ...
